# Streamlit Cloud compatible configuration
postback:
  handlers:
    - type: csv
      output_path: /tmp/postback.csv
    - type: xlsx
      output_path: /tmp/postback.xlsx
    - type: xml
      output_path: /tmp/postback.xml
      root_element: freight_data
      row_element: shipment
    - type: json
      output_path: /tmp/postback.json
      append_mode: false
    # Email handler (configured via Streamlit UI)
    # - type: email
    #   recipient: user@company.com
    #   subject: Freight Data Results
    #   smtp_user: app-email@gmail.com
    #   smtp_pass: app-password
    # Webhook handler (commented out for security)
    # - type: webhook
    #   url: https://example.com/load_update
    #   timeout: 30
    #   batch_size: 50
    #   retry_count: 3
    #   headers:
    #     Content-Type: application/json
    #     Authorization: Bearer your_token_here

enrichment:
  sources:
    - type: tracking_api
      pro_column: "PRO"              # CSV column containing PRO number
      carrier_column: "carrier"      # CSV column containing carrier name
      timeout: 30
      max_retries: 3
      retry_delay: 1
      # Note: Authentication automatically inherited from brokerage configuration
      # Note: API endpoint automatically derived from FF2API base URL

# End-to-End Workflow Settings
endtoend:
  brokerage_key: "augment-brokerage"
  load_api_url: "https://load.prod.goaugment.com/unstable/loads"
  api_timeout: 30
  retry_count: 3
  retry_delay: 1

# Cloud deployment settings
cloud:
  temp_dir: /tmp
  max_file_size_mb: 50
  max_processing_rows: 10000