# Example Streamlit secrets configuration for FF2API Enhanced Workflow
# Copy this to .streamlit/secrets.toml and update with your credentials

# Existing brokerage API keys (for FF2API load processing with token refresh)
[api]
augment-brokerage = "augment-brokerage|your-api-key-here"

# API configuration for FF2API load processing
[api_config]
base_url = "https://api.prod.goaugment.com"
timeout = 30
retry_count = 3
retry_delay = 1

# Hardcoded authentication for tracking API (managed separately)
[tracking_api]
# Option 1: Use bearer token (recommended)
bearer_token = "your-hardcoded-tracking-bearer-token-here"

# Option 2: Use API key (alternative)
# api_key = "your-hardcoded-tracking-api-key-here"

# Hardcoded authentication for load API GET endpoints (retrieving loads by brokerage)
[load_api]
# Option 1: Use bearer token (recommended)
bearer_token = "your-hardcoded-load-api-bearer-token-here"

# Option 2: Use API key (alternative)
# api_key = "your-hardcoded-load-api-key-here"

# Email configuration (optional)
[email]
gmail_user = "your-email@gmail.com"
gmail_password = "your-app-specific-password"
smtp_server = "smtp.gmail.com"
smtp_port = 587

# Authentication
[auth]
APP_PASSWORD = "your-app-password-here"

# Notes:
# - Brokerage API keys are used for FF2API load processing with automatic token refresh
# - tracking_api credentials are used for carrier tracking lookups
# - load_api credentials are used for GET endpoints (retrieving loads, agent events)
# - You can use either bearer_token OR api_key for each service
# - Bearer tokens are recommended as they don't require token refresh